config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :apps
  resources :infos
  resources :posts
  root 'posts#index'

end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
     has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
     validates :name, :number, :location ,:city ,:image ,:description ,:condition ,:date ,presence: true
     belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  #def active_for_authentication? 
   # super && approved? 
  #end 
 # def inactive_message 
   # if !approved? 
  #    :not_approved 
  #  else 
   #   super # Use whatever other message 
   # end 
  #end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 
         has_many :posts
end

app/controllers/Users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
     redirect_to post_path
    end
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end
  def show
  end
  def new
    @post = current_user.posts.build
  end
  def edit
  end
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    def set_post
      @post = Post.find(params[:id])
    end
    def post_params
      params.require(:post).permit(:name, :city, :location, :date, :number, :condition, :description, :image, :done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/apps/index.html.erb
<br><br><br>
<img src="../assets/01.jpg" id="pic">

<br>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/infos/index.html.erb
<br><br><br><br><br>
<br><br>
<!--About Us Section-->
<div class="container">
<div class="row my-4">
<div class="col-md-6">
<img class="img-fluid rounded" src="assets/app.jpg" alt=""></div>
<!-- /.col-lg-8 -->
<div class="col-md-6">
<h1 class="head-style">حوّل المِنصة</h1>
<p class="p1">كيفية التسجيل في منصة انا انسان
<br>حتى يمكنك الإشتراك في منصة انا انسان  او التبليغ عن حالة جديدة عليك الذهاب إلى صفحة 
  التبليغ عن الحالات الانسانية او الضغط على اضافة حالة جديدة في اسفل الصفحة الرئيسية  
سوف يطلب منك إدخال بياناتك الشخصية ( الإسم - الإيميل - كلمة المرور - ) .. يفضل أن تسجل بإسمك الشخصي وذلك لأن إستخدام إسمك الشخصي يسهل هذا التواصل .
كذلك بالنسبة للبريد الإلكتروني يجب أن يكون بريد إلكتروني فعال وذلك لسهولة التواصل
بالنسبه لكلمة المرور فيجب ألا تقل عن 6 أحرف أو أرقام .. ولا يشترط في كلمة المرور صيغه معينة أو مواصفات معينة .. أية 6 أحرف أو أرقام أو كلاهما ستفي بالغرض
بحاله تم مساعده الحاله هناك زر تم الامر في الحاله يجب التعديل عليه..
الأن يمكننا أن نقول لك : أهلاً بك في منصة انا انسان ..</p>
<br><br>
<h1 class="head-style">رسالتنا</h1>
<p class="p1">ندعوُ الإنسان دائماً إلى تقديمِ الخير وتنحية الشرّ بشكلٍ نهائيّ, وأن مِن سِمات الطّبيعة الإنسانيّة، الخصائص الاجتماعيّة لأنّ الإنسان بطبعِهِ لا يستطيعُ العيش بمفردِهِ؛ بل يحتاجُ إلى أنْ يكونَ ضمن مُجتمعٍ،, ومع مجموعةٍ من الأشخاص سواءً في منزلهِ، أو مكان دراستِهِ، أو عملهِ.</p><br/><br/>
</div></div></div>           
<section id="test" class="test bg-grey roomy-60 fix">
<div class="container">
<div class="row">                        
<div class="main_test fix">
<div class="col-md-12 col-sm-12 col-xs-12">
<div class="head_title text-center fix">
<p class="text-bg"><strong>حول المبرمجين</strong> </p>
<p class="p2">نحن مجموعة من المبرمجين المتطوعين في المبادرة الانسانية البرمجة من أجل العراق. تهدف المبادرة الى خدمة وبناء المجتمع من الشعب والى الشعب عن طريق البرمجة</h5></div></div>
<div class="col-md-6">
<div class="test_item fix">
<div class="item_img">
<img class="img-circle" src="assets/FB_IMG_1516295182348.jpg" alt="" />
<i class="fa fa-quote-left"></i></div>
<div class="item_text">
<p class="p21">محمد عيسى</p>
<h6>muhammed.essa@codeforiraq.org</h6>
<p class="p22">"صاحب ومؤسس مبادرة البرمجة من أجل العراق"
</p><br></div></div></div>
<div class="col-md-6">
<div class="test_item fix sm-m-top-30">
<div class="item_img">
<img class="img-circle" src="assets/Doozy+Labs+Responsive+Website+Development+Icon.png" alt="" /><i class="fa fa-quote-left"></i></div>
<div class="item_text">
<p class="p21">المبرمجين</p>
<h6>info@codeforiraq.org</h6>
<p>front-end | Zena Hasan<br> Back-end | Fatima A.Al-khafaji<br> Mobile Application | Rana Abdullah and C4Basra</p>
</div></div></div></div></div></div>
</section>

app/views/layouts/_footer.html.erb
<section id="action" class="action bg-primary roomy-40">
<div class="container">
<div class="row">
<div class="maine_action">
<div class="col-md-12">
<div class="action_item text-center">
<h2 class=" mn">تطوعك غير أجباري لكنه واجب أنساني نحو المجتمع!</h2>
</div></div></div></div></div></section>
<footer id="contact" class="footer action-lage bg-black p-top-80">
<!--<div class="action-lage"></div>-->
<div class="container">
<div class="row">
<div class="widget_area">
<div class="col-md-3">
<div class="widget_item widget_about">
<h5 class="text-white">تواصل معنا</h5>                       
<div class="widget_ab_item m-top-30">
<div class="item_icon">
<i class="fa fa-location-arrow"></i></div>
<div class="widget_ab_item_text">
<h6 class="text-white">الموقع</h6>
<p>
العراق-بغداد
</p></div></div>
<div class="widget_ab_item m-top-30">
<div class="item_icon"><i class="fa fa-envelope-o"></i></div>
<div class="widget_ab_item_text">
<h6 class="text-white">البريد الالكتروني</h6>
<p>info@codeforiraq.org</p>
</div></div></div></div>
<div class="col-md-3">
<div class="widget_item widget_latest sm-m-top-50">
<h5 class="text-white">من نحن</h5>
<p class="m-top-20">نحن مجموعة من المبرمجين المتطوعين في المبادرة الانسانية البرمجة من أجل العراق. تهدف المبادرة الى خدمة وبناء المجتمع من الشعب والى الشعب عن طريق البرمجة.</p>
<div class="widget_latst_item m-top-30">
<div class="item_icon"><img src="/assets/4.png" alt="" /></div>
<div class="widget_latst_item_text"> 
<a href="http://codeforiraq.herokuapp.com/"><strong>
تفضلّ بزيارة الموقع الالكتروني لمبادرة البرمجة من اجل العراق
</strong></div></div></div></div>
<div class="col-md-6">
<div class="widget_item widget_newsletter sm-m-top-50">
<a href=""><h5 class="text-white">شعارنا</h5>
<div class="widget_brand m-top-40">
<img src="/assets/06.png" id="logo1" ></div>
<ul class="list-inline m-top-20">
<li>- <a href="https://www.facebook.com/groups/1093138324163224/"><i class="fa fa-facebook"></i></a></li>
<li><a href="https://codeforiraq.herokuapp.com/index.php"><i class="fa fa-globe"></i></a></li>
<li><a href="https://codeforiraq.herokuapp.com/form.php"><i class="fa fa-dribbble"></i></a>  - </li>
</ul>
</div>
</div>
</div>
</div>
</div>
<div class="main_footer fix bg-mega text-center p-top-40 p-bottom-30 m-top-80">
<div class="col-md-12">
<p class="wow fadeInRight" data-wow-duration="1s">
 جميع الحقوق محفوظة © 2018 | All Rights Reserved © 2018
</p>
</div>
</div>
</footer>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default bootsnav navbar-fixed">
<div class="navbar-top bg-grey fix">
<div class="container">
<div class="row">
<div class="col-md-6">
<div class="navbar-callus text-left sm-text-center">
</div>
</div>
<div class="col-md-6">
<div class="navbar-socail text-right sm-text-center">
</div>
</div>
</div>
</div>
</div>
<!-- Start Top Search -->
<div class="top-search">
<div class="container">
<div class="input-group">
<span class="input-group-addon"><i class="fa fa-search"></i></span>
<input type="text" class="form-control" placeholder="أبحث">
<span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
</div></div></div>
<!-- End Top Search -->
<div class="container"> 
<div class="attr-nav">
<ul>
<li class="search"><a href="#"><i class="fa fa-search"></i></a></li>
</ul>
</div> 
<!-- Start Header Navigation -->
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
<i class="fa fa-bars"></i>
</button>
<a class="navbar-brand" href="#brand">
<img src="/assets/06.png" id="logo">
</a>
</div>
<div class="collapse navbar-collapse" id="navbar-menu">
  <ul class="nav navbar-nav navbar-left">
<% if current_user %>
   Logged in as <strong><%= current_user.email %></strong>.
   <%= link_to 'تعديل', edit_user_registration_path %> |
   <%= link_to "خروج", destroy_user_session_path, method: :delete  %>
 <% else %>
 <li>
   <%= link_to "حساب جديد", new_user_registration_path  %> </li>
   <li>
   <%= link_to "دخول", new_user_session_path %>
</li>
 <% end %>
</ul>
<!-- End Header Navigation -->
<!-- navbar menu -->
<ul class="nav navbar-nav navbar-right">
<li>
<%= link_to "حول المنصة", infos_path %>
</li>
<li>
<%= link_to "حول التطبيق", apps_path %>
</li>
<li>
<%= link_to "تبليغ عن الحالات الانسانية" ,new_post_path %>
</li>
<li>
	<%= link_to "الرئيسية", root_path %> 
</li></ul>
</div></div> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap RTL 3.3.7.3 -->
  <!--bootstrap files-->
  <link href="https://fonts.googleapis.com/css?family=Cairo" rel="stylesheet">
  <link rel="stylesheet" href="assets/css/slick/slick.css"> 
  <link rel="stylesheet" href="assets/css/slick/slick-theme.css">
  <link rel="stylesheet" href="assets/css/animate.css">
  <link rel="stylesheet" href="assets/css/iconfont.css">
  <link rel="stylesheet" href="assets/css/font-awesome.min.css">
  <link rel="stylesheet" href="assets/css/bootstrap.css">
  <link rel="stylesheet" href="assets/css/magnific-popup.css">
  <link rel="stylesheet" href="assets/css/bootsnav.css">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<%= yield %>
<%= render 'layouts/footer' %>
<!--javascript-->
<script src="assets/js/vendor/jquery-1.11.2.min.js"></script>
<script src="assets/js/vendor/bootstrap.min.js"></script>
<script src="assets/js/owl.carousel.min.js"></script>
<script src="assets/js/jquery.magnific-popup.js"></script>
<script src="assets/js/jquery.easing.1.3.js"></script>
<script src="assets/css/slick/slick.js"></script>
<script src="assets/css/slick/slick.min.js"></script>
<script src="assets/js/jquery.collapse.js"></script>
<script src="assets/js/bootsnav.js"></script>
<script src="assets/js/plugins.js"></script>
<script src="assets/js/main.js"></script>
<!--javascript rtl-->
</body>
</html>

app/views/posts/_form.html.erb
<div class="container">
<br><br>
<div class="md-form">
<div class="row">
<div class="col-md-10">
<%= simple_form_for(@post, html: { class: 'form-horizontal' }) do |f| %>
<div class="form-inputs">
<%= f.input :name, label: "الاسم الثلاثي" , required:true %><br>
<%= f.input :city, label: "المحافظة" , collection: ["بغداد","اربيل","دهوك","بصرة","النجف","كربلاء","سليمانية","كركوك","الانبار","الموصل","حلبجة","ذي قار","ميسان","المثنى","واسط","القادسية","ديالى","بابل"], required:true %><br>
<%= f.input :location, label: "اقرب نقطة دالة", required:true %><br>
<%= f.input :number, label: "رقم الهاتف", required:true %><br>
<%= f.input :date, label: "تاريخ الحالة" , required:true %><br>
<%= f.input :condition, label: "اختر حالة", collection: ["نازح", "محتاج", "كوارث", "مساعدات","متطوع"], required:true %><br>
<%= f.input :image, label: "صورة عن الحالة", required:true %><br>
<%= f.input :description, label: "وصف الحالة", as: :text, :input_html => {:rows => 5}  , required:true %><br>
<!--%= f.input :done, label: 'تم الامر', as: :boolean, checked_value: true, unchecked_value: false%-->
<%= f.button :submit, "تأكيد", class:"btn defaul" %><br>
  </div>
<% end %>
</div></div></div></div>

app/views/posts/edit.html.erb
<div class="container">
<br><br><br><br><br><br>
<div class="row">
<div class="col-xs-6 col-md-6"></div>
<div class="col-xs-6 col-md-4">
<h1>تعديل الحالة</h1><br>
</div></div>
<%= render 'form' %>
<br>
<div class="container">
 <div class="row">
  <div class="col-xs-6 col-md-6"></div>
  <div class="col-xs-6 col-md-4">
<%= link_to ' عرض الحالة',@post, class:"btn default" %> 
<%= link_to 'رجوع', posts_path, class:"btn default" %></div>
  <div class="col-xs-6 col-md-4"></div>
</div> 
</div>
</div></div></div></div>
<br><br><br>

app/views/posts/index.html.erb
<br><br><br>
<body data-spy="scroll" data-target=".navbar-collapse">
<!--Home Sections-->

<section class="home" class="home bg-black fix">
<div class="overlay">
<div class="container">
<div class="row">
<div class="main_home text-center">
<div class="col-md-12">
<br> <br><br><br><br><br><br>
<div class="hello_slid">
<div class="slid_item">
<div class="home_text ">
<h1 class="text-white"> يصبح الانسان عظيما تماما بالقدر الذي يعمل فيه من أجل رعاية أخيه الانسان 
<h3 class="text-white">- غاندي -</h3></div>
<center>
</div>
</div></center></div></div></div></div></div>
</section> 
<!--Featured Section-->
<section id="features" class="features">
<div class="container">
<div class="row">
<div class="main_features fix roomy-70">
<div class="col-md-4">
<div class="features_item sm-m-top-30">
<div class="f_item_icon">
<i class="fa fa-tablet"></i>
</div>
<div class="f_item_text">
<h3>حمّل تطبيق الجوال </h3><br>
<p>بأمكانكم ايضا تحميل تطبيق "أنا أنسان" على هواتفكم من المتجر الخاص بكم.</p></div></div></div>
<div class="col-md-4"><div class="features_item sm-m-top-30">
<div class="f_item_icon"><i class="fa fa-bullhorn"></i></div>
<div class="f_item_text">
<h3>أذا أحسست بألالم فأنت "حي" وأذا أحسست بألام ألأخرين فأنت "أنسان"</h3>
<p>بأمكان أي فرد التبليغ عن حالة أنسانية, ونحن سنعلن عنها في الموقع الالكتروني.</p>
</div></div></div>
<div class="col-md-4">
<div class="features_item sm-m-top-30">
<div class="f_item_icon">
<i class="fa fa-handshake-o"></i>
</div>
<div class="f_item_text">
<h3>العطاء .. بذرة من نقاء تثمر خيرا وصفاء</h3>
<p>نحن نؤمن بأن كل فرد قادر على تقديم الخدمات التي يحتاجها المجتمع, فمن اعطى وقت الحاجة كانت عطيته مضاعفة, قال تعالى :"فمن يعمل مثقال ذرة خيرا يره"</p>
</div></div></div></div></div></div></div>
</section>
<br><br>
<div class="container">
     <hr>
    <!--div class="row">
        <div class="col-md-3 col-md-offset-3">
    <h3>حمل التطبيق الان </h3>
        </div>
    </div-->
</div>
</p>
<p id="notice"><%= notice %></p>
<div class="container">
<h1 style="font-family:'Droid Arabic Naskh', serif; line-height:60px;">عرض الحالات</h1></div>
<% @posts.each do |post| %>
<div class="container">
<div class="row">
<div class="row">
    <div class="col-md-4">
        <%= image_tag post.image.url(:large) %><hr>
    </div><br>
  <div class="col-md-3">
      <%= post.city %><br>
      <%= post.date %><br>
      <%= post.description %>
  </div>
<div class="col-md-5">
<%= link_to 'عرض', post, class:"btn default" %>
<% if post.user == current_user %>
    <%= link_to 'تعديل', edit_post_path(post), class:"btn default" %>
    <%= link_to 'حذف', post, method: :delete, data: { confirm:'هل انت متأكد؟' }, class:"btn default" %>
<% end %>
</div>
</div>
<% end %>
</div></div>

<br>
<div class="container">
<%= link_to 'اضافة حالة جديدة', new_post_path, class:"btn default"%>
</div></div></div></div></div>
</div><br><br><br><br><br><br>


 

app/views/posts/new.html.erb
<br><br><br><br><br><br>
<div class="container">
<div class="row">
<div class="col-xs-6 col-md-6"></div>
<div class="col-xs-6 col-md-4">
<h1>حالة جديدة</h>
</div></div>
<%= render 'form' %>
<br>
<div class="container">
   <div class="row">
<div class="col-xs-6 col-md-6"></div>
<div class="col-xs-6 col-md-4">
<%= link_to 'العودة', posts_path, class:"btn default" %>
</div></div></div>
</div>
<br><br><br><br>

app/views/posts/show.html.erb
<br><br><br><br><br><br>
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <label>الاسم:</label>
  <%= @post.name %>
</p>

<p>
   <label>االمحافظة:</label>
  <%= @post.city %>
</p>

<p>
  <label>اقرب نقطة دالة :</label>
  <%= @post.location %>
</p>

<p>
 <label>تاريخ الحالة :</label>
  <%= @post.date %>
</p>

<p>
 <label>رقم الهاتف:</label>
  <%= @post.number %>
</p>
<p>
  <%= image_tag @post.image.url(:medium) %>
</p>
<p>
<label>الحالة </label>
  <%= @post.condition %>
</p>

<p>
 <label>وصف عن الحالة :</label>
  <%= @post.description %>
</p>
<div class="container">
<!--% if post.editable_by(current_user) %>
  <%= link_to 'تعديل الحالة', edit_post_path(@post), class:"btn default"%>
<!--% end %-->
<%= link_to 'الرجوع', posts_path, class:"btn default" %>
</div>
</div>
<br><br><br><br><br><br>